name: Python package

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r UI/requirements.txt
        sudo apt-get update
        sudo apt-get install -y python3-pyqt5  # Install PyQt5 system dependencies
        pip install PyQt5  # Install PyQt5 Python package

    - name: Run tests
      run: |
        python -m unittest discover -s tests
